name: Deploy backe to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USERNAME }}
          APP_DIR: /cyber/cyber_backend
          PORT: ${{ secrets.PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          ssh $USER@$HOST << EOF
          set -e

          mkdir -p "$APP_DIR"
          cd "$APP_DIR"

          if [ ! -d .git ]; then
            git clone https://github.com/otabek0311/Phone_Market_Backend.git .
          else
            git pull origin main
          fi

          cat > .env << EOL
          PORT=${PORT}
          DB_NAME=${DB_NAME}
          DB_PASSWORD=${DB_PASSWORD}
          JWT_SECRET=${JWT_SECRET}
          EOL

          npm install
          npm run build

          pm2 delete cyber_backend || true
          pm2 start dist/main.js --name cyber_backend
          pm2 save
          EOF
